name: Build Docker images

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [11-jre, 17-jre]
        os: [alpine, debian]
    env:
      repo: "govpf/springboot-base"
    steps:

    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Build
      uses: docker/build-push-action@v2.7.0
      with:
        context: ./${{ matrix.versions }}/${{ matrix.os }}
        file: ./${{ matrix.versions }}/${{ matrix.os }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: false

    - name: Build, ONBUILD image
      uses: docker/build-push-action@v2.7.0
      with:
        context: ./${{ matrix.versions }}/${{ matrix.os }}
        file: ./${{ matrix.versions }}/${{ matrix.os }}/Dockerfile.onbuild
        platforms: linux/amd64
        pull: true
        push: false
